import = ["~/.config/alacritty/tokyonight_night.toml"]

live_config_reload = true

[window.dimensions]
columns = 150
lines = 35

[window.padding]
x = 5
y = 5

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font"
style = "Light"

[selection]
save_to_clipboard = true