
# Source global definitions
echo ">>>>>>"

if [ -f $HELPER_DOTFILES_HOME/bash/myzshrc.sh ]; then
    . $HELPER_DOTFILES_HOME/bash/myzshrc.sh
fi

alias k=kubectl
complete -F __start_kubectl k

alias luamake=$HOME/.config/nvim/lua-language-server/3rd/luamake/luamake

# add Pulumi to the PATH
export PATH=$PATH:$HOME/.pulumi/bin

[ -s ~/.luaver/luaver ] && . ~/.luaver/luaver
